# This rule is not used by the project parallax itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the batchops.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: parallax
    app.kubernetes.io/managed-by: kustomize
  name: listjob-editor-role
rules:
- apiGroups:
  - batchops.io
  resources:
  - listjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batchops.io
  resources:
  - listjobs/status
  verbs:
  - get
