# This rule is not used by the project parallax itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to batchops.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: parallax
    app.kubernetes.io/managed-by: kustomize
  name: listcronjob-viewer-role
rules:
- apiGroups:
  - batchops.io
  resources:
  - listcronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batchops.io
  resources:
  - listcronjobs/status
  verbs:
  - get
