apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  database: {{ .Values.postgres.database | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
type: Opaque
data:
  token: {{ "test-token-123" | b64enc | quote }}
