name: 'Setup Test Environment'
description: 'Set up Go, Kind, and Docker Buildx for testing'
inputs:
  go-version:
    description: 'Go version to install'
    required: false
    default: '1.23'
  install-kind:
    description: 'Whether to install Kind'
    required: false
    default: 'true'
  install-helm:
    description: 'Whether to install Helm'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Kind
      if: ${{ inputs.install-kind == 'true' }}
      shell: bash
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.24.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Install Helm
      if: ${{ inputs.install-helm == 'true' }}
      uses: azure/setup-helm@v4