name: Helm Chart Validation

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - 'api/**'
      - 'internal/controller/**'
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
      - 'api/**'
      - 'internal/controller/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Set up yq
        uses: mikefarah/yq@master

      - name: Generate Helm chart
        run: |
          if ! make helm-generate; then
            echo "::error::Failed to generate Helm chart. Run 'make helm-generate' locally to fix."
            exit 1
          fi

      - name: Lint Helm chart
        run: |
          if ! make helm-lint; then
            echo "::error::Helm chart linting failed. Run 'make helm-lint' locally to see the issues."
            exit 1
          fi

      - name: Template Helm chart
        run: |
          if ! make helm-template; then
            echo "::error::Failed to template Helm chart. Run 'make helm-template' locally to debug."
            exit 1
          fi

      - name: Check CRD sync
        run: |
          if ! diff -r config/crd/bases/ charts/parallax/crds/; then
            echo "::error::CRDs are out of sync. Run 'make helm-crds' locally to update."
            exit 1
          fi

      - name: Check RBAC sync
        run: |
          if ! diff config/rbac/role.yaml charts/parallax/generated/rbac-rules.yaml; then
            echo "::error::RBAC rules are out of sync. Run 'make helm-rbac-rules' locally to update."
            exit 1
          fi 